# Generated by Django 5.2.5 on 2025-08-18 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EndoscopyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('WLI', '白光影像'), ('NBI', '窄頻影像')], max_length=3, verbose_name='影像類型')),
                ('original_image', models.FileField(upload_to='original_images/%Y/%m/%d/', verbose_name='原始影像檔案')),
                ('yolo_output_image', models.FileField(blank=True, null=True, upload_to='yolo_output_images/%Y/%m/%d/', verbose_name='YOLO輸出影像')),
                ('review_status', models.CharField(choices=[('pending_review', '待審核'), ('reviewed_approved', '已審核(正確)'), ('reviewed_corrected', '已審核(修正)')], default='pending_review', max_length=20, verbose_name='審核狀態')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='審核時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '內視鏡影像',
                'verbose_name_plural': '內視鏡影像',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='批次名稱')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('import_method', models.CharField(default='manual_upload', max_length=50, verbose_name='匯入方式')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '影像批次',
                'verbose_name_plural': '影像批次',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_label', models.IntegerField(choices=[(0, '瘜肉'), (1, '腫瘤')], verbose_name='病兆類別')),
                ('source_type', models.CharField(choices=[('model_generated', '模型產生'), ('doctor_added', '醫師新增')], max_length=20, verbose_name='標記來源')),
                ('model_box', models.JSONField(blank=True, null=True, verbose_name='模型標記框 (AI)')),
                ('doctor_box', models.JSONField(blank=True, null=True, verbose_name='醫師標記框 (Ground Truth)')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已由醫師刪除')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='reviewer.endoscopyimage', verbose_name='所屬影像')),
            ],
            options={
                'verbose_name': '標記資訊',
                'verbose_name_plural': '標記資訊',
            },
        ),
        migrations.AddField(
            model_name='endoscopyimage',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reviewer.imagebatch', verbose_name='所屬批次'),
        ),
    ]
