# Generated by Django 5.2.5 on 2025-08-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endoscopyimage',
            name='doctor_diagnosis',
            field=models.CharField(choices=[('polyp_only', '只有瘜肉'), ('tumor_only', '只有腫瘤'), ('polyp_and_tumor', '有瘜肉和腫瘤'), ('negative', '無病兆'), ('undefined', '未定義')], default='undefined', max_length=20, verbose_name='醫師最終診斷'),
        ),
    ]
